project:
  type: book
  output-dir: ../docs
  preview: 
    port: 4200

book:
  title: "Equivalence of neural field dynamics with different embedding dimensionality"
  subtitle: "![](epfl.svg){width=30%}"
  author:
    - name: Nicole Vadot
    - name: (Supervisor) Valentin Schmutz
    - name: (Supervisor, Director of LCN) Wulfram Gerstner
  date: last-modified
  chapters:
    - index.qmd
    - chapters/1_intro.qmd
    - chapters/2_neural_fields.qmd
    - chapters/3_mappings.qmd
    - chapters/4_locality.qmd
    - chapters/5_conclusion.qmd
    - references.qmd
  appendices:
    - appendices/A_fixed_points.qmd
    - appendices/B_mean_patterns.qmd
  repo-url: https://github.com/ninivert/lcnthesis
  downloads: [pdf, epub]
  language: en

bibliography:
  - references.bib
  - references2.bib
csl: ieee-with-url.csl

# cache: true

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: darkly
    toc: true
    toc-depth: 4
    fig-format: svg
    # html-math-method:
    #   method: mathjax
    #   url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  pdf:
    # keep-tex: true
    pdf-engine: pdflatex
    documentclass: scrreprt
    classoption: abstract
    papersize: a4
    link-citations: true
    colorlinks: true
    fontsize: 12pt
    include-in-header: 
      - text: |
          \usepackage{authblk}
          \usepackage{makeidx}
          \makeindex
      - file: macros.tex