project:
  type: book
  output-dir: ../docs
  preview: 
    port: 4200

book:
  title: "Neural field dynamics and equivalence of embeddings in different dimensions"
  author:
    - name: Nicole Vadot
    # - name: Valentin Schmutz
    #   acknowledgements: Thesis Supervisor
  date: last-modified
  abstract: |
    Literature around the study of biological networks of neurons shows evidence that neurons can be spatially structured, leading to the developement of neural field models. In early papers, this structure emerges from the observation that functionally similar neurons tend to share similar positions in the cortex. Later it has been shown that not only the physical position of the neurons can be used to parametrize their function, but also their location in more abstract "embedding spaces", for example a space of "neuron celltypes".

    Decoupling the embedding space from the physical position of neurons on the cortical sheet leads to asking the question of uniqueness of the embedding space. Given an embedding space and neural dynamics thereon, do there exist other embedding spaces which can express the same behavior ? Is there a "natural" choice for the embedding space ?

    In this work, we show that the answer to the second question is highly nontrivial because given some neural dynamics, we can find multiple equivalent embedding spaces in different dimensions. We illustrate this using a toy example of a 2 (or 3)-dimensional embedding that is mapped to an equivalent 1-dimensional embedding. This is done by applying measurable bijective mappings $S : [0,1]^2 \mapsto [0,1]$, which we additionally show are well-behaved under numerical simulation schemes. In this, we exploit the key concept of "locality", which expresses the property of (not necessarily continuous, or possibly fractal) neural fields, in which neighbouring neurons in the embedding space *tend* to have similar functions.
  chapters:
    - index.qmd
    - chapters/1_intro.qmd
    - chapters/2_neural_fields.qmd
    - chapters/3_mappings.qmd
    - chapters/4_locality.qmd
    - chapters/5_conclusion.qmd
    - references.qmd
  appendices:
    - appendices/A_fixed_points.qmd
    - appendices/B_zcurve.qmd
    - appendices/C_mean_patterns.qmd
  repo-url: https://github.com/ninivert/lcnthesis
  downloads: [pdf, epub]
  language: en

bibliography:
  - references.bib
  - references2.bib
csl: ieee-with-url.csl

cache: true

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: darkly
    toc: true
    toc-depth: 4
    fig-format: svg
    # html-math-method: mathjax
    # include-in-header: 
    #   - text: |
    #       <script src="/js/mathjax/es5/tex-chtml.js"></script>
    #       <script>
    #         window.MathJax = {
    #           loader: {
    #             // load: ['[tex]/physics']
    #           },
    #           tex: {
    #             // packages: {'[+]': ['physics']}
    #           }
    #         };
    #         </script>
    #       </script>
  epub:
    toc: true
    date: last-modified
  pdf:
    pdf-engine: pdflatex
    documentclass: scrreprt
    classoption: abstract
    papersize: a4
    keep-tex: true
    link-citations: true
    colorlinks: true
    include-in-header: 
      - text: |
          \usepackage{makeidx}
          \makeindex
      - file: macros.tex